version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: epidb
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - epi-network

  springboot-app:
    build: .
    container_name: epi-management-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/epidb
      - spring.datasource.username=root
      - spring.datasource.password=secret
    depends_on:
      - mysql
    networks:
      - epi-network

networks:
  epi-network:
